### PR TITLE
Added container without external dependencies.

### PR DESCRIPTION
**Pull request by KaiSzuttor**

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
@mkuron any idea why the docker command failed there? 
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/54764

**Comment by mkuron** [comment]
18.04: no idea. Rocm: that‘s a Docker/apt bug that sometimes strikes. S390x: maybe Gitlab was restarted during the job.

**Comment by mkuron** [comment]
Your .gitlab-ci.yml section and your Dockerfile need matching names.

**Comment by KaiSzuttor** [comment]
``` bash
root@5969beee7a0c:/tmp# git clone -b r2c https://github.com/mkuron/rocFFT.git
Cloning into 'rocFFT'...
fatal: Remote branch r2c not found in upstream origin
```

**Comment by KaiSzuttor** [comment]
@mkuron please fix the rocm container

**Comment by mkuron** [comment]
Sorry, the rocfft build should now work again.

**Comment by KaiSzuttor** [comment]
any idea @mkuron?
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/55648

**Pull request merged**
