### PR TITLE
Test all images.

### LINKED ISSUE #88: test all containers for espresso compatibility

### PR DESCRIPTION
**Pull request by KaiSzuttor**
Fixes #88

### CODE REVIEW

**Comment by jngrad** [comment]
You need `.test_py3_template` for exotic archs.

**Comment by jngrad** [comment]
I think you accidentally moved `Dockerfile-wo-dependencies` into the python3 folder. You need to do a copy instead and test the original version with `.test_template_v40`. Otherwise on espresso the 4.0 branch will not pass CI anymore and the master branch will not pass CI until we merge a fixed yml file (we did the same mistake with the i386 container recently).

**Comment by KaiSzuttor** [comment]
thanks @jngrad, I added the build and test again

**Comment by fweik** [comment]
Is there any reason why this isn't merged yet?

**Comment by jngrad** [comment]
@fweik As discussed in the coding day, the pipeline would take too long. We have two open PR to remediate this: #102 to only build and test a container if it changed, and #96 to re-enable cache.

**Comment by fweik** [comment]
I don't understand what you mean by "We won't be able to do hotifxing anymore.", if I understand your consideration correctly the process took 9h befor, which isn't exactly fast. Also we can always make the CI use the last good version if something breaks.

**Pull request merged**
