### PR TITLE
set static tlmgr repository

### LINKED ISSUE #126: TeXlive url unreachable
When building the `cuda:10.1` image, the tlmgr command can fail silently if an URL cannot be reached, causing a failure in the espresso weekly build (espressomd/espresso#3038, [logfile](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/143405)).

Expected behavior:
```
INFO[1311] args: [-c tlmgr init-usertree     && tlmgr install pgf tikz-3dplot revtex units mhchem chemgreek todonotes upquote framed subfigure cleveref     && tlmgr install lm stmaryrd 2>&1 || :     && updmap -user] 
(running on Debian, switching to user mode!)
tlmgr: package repository http://ctan.space-pro.be/tex-archive/systems/texlive/tlnet (verified)
[1/11, ??:??/??:??] install: chemgreek [7k]
[2/11, 00:00/00:00] install: cleveref [28k]
```
Problematic behavior: failure to reach the URL on [bwCloud](https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/142221), [elk](https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/142256) and coyote4 (outside CI):
```
INFO[1310] args: [-c tlmgr init-usertree     && tlmgr install pgf tikz-3dplot revtex units mhchem chemgreek todonotes upquote framed subfigure cleveref     && tlmgr install lm stmaryrd 2>&1 || :     && updmap -user] 
(running on Debian, switching to user mode!)

/usr/bin/tlmgr: TLPDB::from_file could not download https://ftp.agdsn.de/pub/mirrors/latex/dante/systems/texlive/tlnet/tlpkg/texlive.tlpdb;
/usr/bin/tlmgr: maybe the repository setting should be changed.
```

Manually creating the `cuda:10.1` image is possible on my desktop machine but not on coyote4 due to the unreachable URL. In CI, the URL is sometimes unreachable in bwCloud, and on elk there is only one data point, where it was unreachable. The URL is selected at random in a list of known mirrors.

Unfortunately tlmgr doesn't return an error code when that happens, so I'll have to add more bash commands to grep the stderr output, such as (doesn't work but probably close):
```bash
RUN ... \
    && ! tlmgr install ... 2>&1 | grep --quiet "TLPDB::from_file could not download" \
    && ...
```
This way the build fails if the LaTeX packages are not installed, and the job has to be retried.

### PR DESCRIPTION
**Pull request by mkuron**
fixes #126

@jngrad

### CODE REVIEW

**Comment by jngrad** [comment]
A cuda image was just tested on a coyote with outdated nvidia driver ([logfile](https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/143661)). Should we update all coyotes with nvidia driver 430.23 (CUDA 10.2)? The `cuda:10.1` image confirmed this driver version works well in our environment.

**Comment by mkuron** [comment]
coyote8 has a Fermi card, which is not supported by drivers beyond 390. That's why it does not have the _cuda_ tag, only the _cuda-fermi_ tag. All other coyotes were upgraded from 418 to 430 a few weeks ago.

Since we don't actually run the espresso tests in the docker repository, the driver mismatch (or even running an AMD image on a machine with an Nvidia GPU or vice versa) does not matter. The actual problem here is that the nvidia docker runtime checks the driver version against the image metadata. Perhaps we should add the `cuda` tag to the docker tests. This is not a new issue; it should have existed since we switched to nvidia-docker-v2 in January.

**Comment by mkuron** [comment]
Hmm, I think we could just set `NVIDIA_DISABLE_REQUIRE` in the runner configuration to get rid of that problem. I'll check.

**Comment by mkuron** [comment]
@jngrad, I have now added `environment = ["NVIDIA_DISABLE_REQUIRE=1"]` to /etc/gitlab-runner/config.toml on all runners except for coyote3, which is currently broken.

**Pull request merged**
