### PR TITLE
Disable image build cache

### PR DESCRIPTION
**Pull request by mkuron**
Temporary workaround for #92‘s corrupted images

@jngrad

### CODE REVIEW

**Comment by jngrad** [comment]
Should we increase the timeout for the build stage?

**Comment by mkuron** [comment]
Sure, give it a try. I'm at a conference this week and won't have much time to look into this, so it would be good if you could take care of it.

**Comment by jngrad** [comment]
The master branch just failed because the line
https://github.com/espressomd/docker/blob/da1f5cbcd1e16d4e02c9a7bdfe39ac3ed48d766e/maintainer/docker_build.sh#L22
builds the image again, which causes the same files/folders/symlinks to be created again, leading to name conflicts. This was not an issue before since the cached layers were re-used during the second build.

Before kaniko, docker was used to build once and push to 2 destinations. However I could not find a command line option in kaniko to push an image without building it first, and couldn't experiment with the kaniko image as it doesn't seem to run in interactive mode.

**Comment by mkuron** [comment]
Ok, I‘ll try to adapt the build script this evening to only build once.

**Pull request merged**
