### PR TITLE
Reduce number of CUDA images

### PR DESCRIPTION
**Pull request by jngrad**
Required for espressomd/espresso#3611

### CODE REVIEW

**Comment by jngrad** [comment]
The Ubuntu 20.04 image failed to build during the second `apt-get` command with:
```
Error processing tar file(exit status 1): write /usr/share/icons/ubuntu-mono-dark/
status/24/gnome-netstatus-0-24.svg: no space left on device
```
According to the docs, the runners are limited to 7 GB of RAM and 14 GB of disk space. The image size was 6.0 GB before that PR and will be 6.8 GB after that PR. Peak RAM consumption during the `apt-get` command according to `/usr/bin/time -v` is 66 MB on my machine. Could it be that the runner doesn't store the layers on the SSD?

Here is a break down of the data fetched from the repository:
* packages from ubuntu-packages.txt: 611 newly installed, need to get 346 MB of archives, 1958 MB of additional disk space will be used.
* other packages:
   * after this PR: 326 newly installed, need to get 1716 MB of archives, 5190 MB of additional disk space will be used.
   * before this PR: 132 newly installed, need to get 1560 MB of archives, 4511 MB of additional disk space will be used.

**Comment by RudolfWeeber** [comment]
This might be "solvable" by adding an 
apt-get clean
before the 2nd apt-get install. This will maybe clear some cached downloaded archives.

**Comment by jngrad** [comment]
`apt-get -s clean` returns 3 folders, two of which don't exist and the third one is empty. We're probably short by a few hundred megabytes. I'm moving the doxygen package and its dependencies to the Ubuntu 18.04 image to save 400 MB. That's a shame, because the latest doxygen had a much better checking mechanism and helped me fix a few mistakes. Hopefully we'll get the `cuda:latest` image in a few weeks; without Clang there will be plenty of space to install the latest doxygen.

**Comment by fweik** [comment]
Why is `texlive` still needed? And did you check that it does not install extra `recommended` packages? For texlive this is an issue because it installs GB of documentation

**Comment by jngrad** [comment]
`texlive` provides `bibtex`, which is needed to create a bibliography in doxygen. We only install ` tex-common texlive-base texlive-binaries`. The folder `/usr/share/doc` is only 37 MB in size. Transferring doxygen and texlive to Ubuntu 18.04 worked [[2]](https://github.com/jngrad/espresso-docker/runs/618462116?check_suite_focus=true).

**Comment by fweik** [comment]
Adding `--no-install-recommends` saves 500+MB on texlive-base alone...

**Comment by jngrad** [comment]
doxygen+graphviz+texlive only account for 390 MB...
```
$> docker image ls
REPOSITORY    TAG               IMAGE ID          CREATED           SIZE
ubuntu        20-gpu            9ab2c67c65b9      31 hours ago      6.77GB
ubuntu        20-gpu-nolatex    7b9ddf4945b5      47 minutes ago    6.48GB
```
`--no-install-recommends` saves space on other packages. I'll have to run all espresso jobs again with that new image to make sure that nothing broke.

**Comment by fweik** [comment]
>  I'll have to run all espresso jobs again with that new image to make sure that nothing broke.

Wouldn't you see this when the versions are actually dumped on the espresso repo?

**Pull request merged**
