### PR TITLE
ROCm 3.8

### PR DESCRIPTION
**Pull request by mkuron**
@jngrad

### CODE REVIEW

**Comment by jngrad** [comment]
@mkuron I tried using the Ubuntu 20.04 version of ROCm 3.8 (f72c54cb), but I keep getting the following failure:
```
113/158 Test #156: p3m_tuning_exceptions .............................***Failed    3.80 sec
.........
python3: /home/espresso/espresso/src/utils/include/utils/math/bspline.hpp:33: std::enable_if_t<((order > 0) && (order <= 7)), T> Utils::bspline(int, T) [with int order = 7; T = double; std::enable_if_t<((order > 0) && (order <= 7)), T> = double]: Assertion `(x >= -0.5)' failed.
[3c6b4353db72:21151] *** Process received signal ***
[3c6b4353db72:21151] Signal: Aborted (6)
[3c6b4353db72:21151] Signal code:  (-6)
[3c6b4353db72:21151] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f21e620f210]
[3c6b4353db72:21151] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f21e620f18b]
[3c6b4353db72:21151] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f21e61ee859]
[3c6b4353db72:21151] [ 3] /lib/x86_64-linux-gnu/libc.so.6(+0x25729)[0x7f21e61ee729]
[3c6b4353db72:21151] [ 4] /lib/x86_64-linux-gnu/libc.so.6(+0x36f36)[0x7f21e61fff36]
[3c6b4353db72:21151] [ 5] /home/espresso/espresso/build/src/core/EspressoCore.so(std::enable_if<(((7)>(0)))&&((7)<=(7)), double>::type Utils::bspline<7, double>(int, double)+0x341)[0x7f21e59cbf41]
[3c6b4353db72:21151] [ 6] /home/espresso/espresso/build/src/core/EspressoCore.so(InterpolationWeights<7> p3m_calculate_interpolation_weights<7>(Utils::Vector<double, 3ul> const&, Utils::Vector<double, 3ul> const&, p3m_local_mesh const&)+0x131)[0x7f21e59cc0c1]
[3c6b4353db72:21151] [ 7] /home/espresso/espresso/build/src/core/EspressoCore.so(dp3m_dipole_assign(ParticleRange const&)+0x224)[0x7f21e59d4c54]
[3c6b4353db72:21151] [ 8] /home/espresso/espresso/build/src/core/EspressoCore.so(Dipole::calc_long_range_force(ParticleRange const&)+0x20d)[0x7f21e59e463d]
[3c6b4353db72:21151] [ 9] /home/espresso/espresso/build/src/core/EspressoCore.so(force_calc(CellStructure&, double)+0x132)[0x7f21e58f6032]
[3c6b4353db72:21151] [10] /home/espresso/espresso/build/src/core/EspressoCore.so(integrate(int, int)+0x307)[0x7f21e59147c7]
[3c6b4353db72:21151] [11] /home/espresso/espresso/build/src/core/EspressoCore.so(mpi_integrate(int, int)+0xc7)[0x7f21e58cf517]
[3c6b4353db72:21151] [12] /home/espresso/espresso/build/src/core/EspressoCore.so(time_force_calc(int)+0x42)[0x7f21e5976f22]
[3c6b4353db72:21151] [13] /home/espresso/espresso/build/src/core/EspressoCore.so(+0x26ea83)[0x7f21e59d1a83]
[3c6b4353db72:21151] [14] /home/espresso/espresso/build/src/core/EspressoCore.so(dp3m_adaptive_tune(char**)+0xaf8)[0x7f21e59d41b8]
[3c6b4353db72:21151] [15] /home/espresso/espresso/build/src/python/espressomd/magnetostatics.so(+0x2264b)[0x7f21b83c764b]
[3c6b4353db72:21151] [16] /usr/lib/python3/dist-packages/numpy/random/bit_generator.cpython-38-x86_64-linux-gnu.so(+0xe389)[0x7f21bc860389]
[3c6b4353db72:21151] [17] /home/espresso/espresso/build/src/python/espressomd/magnetostatics.so(+0x1ed9c)[0x7f21b83c3d9c]
[3c6b4353db72:21151] [18] /home/espresso/espresso/build/src/python/espressomd/magnetostatics.so(+0x2445f)[0x7f21b83c945f]
[3c6b4353db72:21151] [19] /home/espresso/espresso/build/src/python/espressomd/magnetostatics.so(+0x32fe9)[0x7f21b83d7fe9]
[3c6b4353db72:21151] [20] /usr/lib/python3/dist-packages/numpy/random/bit_generator.cpython-38-x86_64-linux-gnu.so(+0xe389)[0x7f21bc860389]
[3c6b4353db72:21151] [21] /home/espresso/espresso/build/src/python/espressomd/magnetostatics.so(+0x1ed9c)[0x7f21b83c3d9c]
[3c6b4353db72:21151] [22] /home/espresso/espresso/build/src/python/espressomd/magnetostatics.so(+0x2445f)[0x7f21b83c945f]
[3c6b4353db72:21151] [23] /home/espresso/espresso/build/src/python/espressomd/magnetostatics.so(+0x30a35)[0x7f21b83d5a35]
[3c6b4353db72:21151] [24] /usr/lib/python3/dist-packages/numpy/random/bit_generator.cpython-38-x86_64-linux-gnu.so(+0xe389)[0x7f21bc860389]
[3c6b4353db72:21151] [25] /home/espresso/espresso/build/src/python/espressomd/actors.so(+0xfffc)[0x7f21b8e23ffc]
[3c6b4353db72:21151] [26] /home/espresso/espresso/build/src/python/espressomd/actors.so(+0x1021f)[0x7f21b8e2421f]
[3c6b4353db72:21151] [27] /home/espresso/espresso/build/src/python/espressomd/actors.so(+0x1765a)[0x7f21b8e2b65a]
[3c6b4353db72:21151] [28] /usr/lib/python3/dist-packages/numpy/random/bit_generator.cpython-38-x86_64-linux-gnu.so(+0xe389)[0x7f21bc860389]
[3c6b4353db72:21151] [29] /home/espresso/espresso/build/src/python/espressomd/actors.so(+0xfffc)[0x7f21b8e23ffc]
[3c6b4353db72:21151] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 0 on node 3c6b4353db72 exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```
It also fails sometimes when called directly with `mpiexec -n 1 ./pypresso testsuite/python/p3m_tuning_exceptions.py`

**Comment by mkuron** [comment]
That‘s odd. That part of the code isn‘t even compiled by hipcc but by the host compiler. Does it only happen in the Ubuntu 20.04 image and not in 18.04? If so, that must be due to the newer gcc version. But don‘t we already have other images based on 20.04?

**Comment by jngrad** [comment]
It doesn't happen on the Ubuntu 18.04 version of ROCm 3.8, unless I use 2 MPI ranks. The test should be able to run with any number of MPI ranks. I think it's a bug in the dipolar P3M code, I'll open a ticket with a MWE.

**Comment by jngrad** [comment]
Removing the fragile test fixes the failure. However when running all tests with `make -j32 check_python` I get random timeouts:
```
The following tests FAILED:
	 58 - rotational_inertia (Timeout)
	 63 - constant_pH (Timeout)
	 80 - integrator_npt (Timeout)
	 92 - collision_detection (Timeout)
```
This is always this subset of tests that times out randomly. This doesn't happen on the Ubuntu 18.04 version. When running these tests individually, or in the testsuite with only 2 parallel jobs, they are not timing out.

Having an Ubuntu 20.04 ROCm image is the last remaining task for espressomd/espresso#3611.

**Comment by mkuron** [comment]
Hmm, it's unlikely that that is ROCm-releated either. Are we using different compiler or optimization flags compared to our other CI jobs?

**Pull request closed without merging**
