### PR TITLE
Deploy stage

### PR DESCRIPTION
**Pull request by KaiSzuttor**
extends on #94

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
yes, you cannot have non-unique job names in the pipeline

**Comment by KaiSzuttor** [comment]
this seems to do the job but I'm quite unhappy with the duplication and the additional complexity that comes with kaniko.

**Comment by mkuron** [comment]
The job names are confusing now. The build stage has xxx:test, the test stage has test/xxx and the deploy stage has xxx. Once that is cleaned up, please merge.

The kaniko solution is more secure than docker-build because it doesn‘t require root privileges on the host machine. Besides the caching that‘s currently broken, I think kaniko works reasonably well.

**Comment by KaiSzuttor** [comment]
I don't question kaniko itself, but the fact that we have to add so much noise to our CI config

**Comment by KaiSzuttor** [comment]
> The job names are confusing now. The build stage has xxx:test, the test stage has test/xxx and the deploy stage has xxx. Once that is cleaned up, please merge.

The whole config is confusing now due to the additional stage. We cannot have the same job name twice, so we have to come up with some arbitrary naming.

**Comment by mkuron** [comment]
Also, the additional stage makes more sense than what we had previously. Now the image is only pushed after the tests pass.

**Comment by KaiSzuttor** [comment]
why seems the build time for the intel 15 image to monotonically increase?

**Pull request merged**
