### PR TITLE
Update dependencies for 4.2 and add intel:19 image

### PR DESCRIPTION
**Pull request by jngrad**
- `intel:19` will replace `intel:18` in CI of espresso 4.2
- add new setuptools Python dependency (fixes failed CI on master)
- remove unused Python dependencies
- add blas and lapack libraries
- rollback to a stable version of kaniko

### CODE REVIEW

**Comment by mkuron** [comment]
Try downgrading kaniko to debug-v.0.16.0.

https://console.cloud.google.com/gcr/images/kaniko-project/GLOBAL/executor

**Comment by jngrad** [comment]
The error persists: `failed to execute command: extracting fs from image`

Same reason as before:
- `removing whiteout .wh.dev: unlinkat //dev/pts/ptmx: operation not permitted`

Plus new ones:
- `removing whiteout etc/.wh.hostname: unlinkat /etc/hostname: device or resource busy`
- `mkdir /lib64: file exists`

**Comment by jngrad** [comment]
Running kaniko locally: I can create the image from scratch just fine, and re-create it with the cache enabled to update our container registry, but I cannot pull the image: `docker: failed to register layer: Error processing tar file(exit status 1): failed to ...` with a different reason depending on the image. For the CentOS7 image, I get the same error message as in [this thread](https://askubuntu.com/questions/1194270/mknod-on-cifs-samba-operation-not-permitted-when-pulling-with-docker).

With kaniko v0.15 I can locally build, update the cache and pull the image.

**Comment by mkuron** [comment]
The cache might have been poisoned by the new version. You'll need to delete the cache registry at https://gitlab.icp.uni-stuttgart.de/espressomd/docker/container_registry and any cache volumes on elk using `docker system prune --volumes --all --force`.

**Comment by jngrad** [comment]
I also thought about corrupted layers and deleted the latest `gitlab.icp.uni-stuttgart.de:4567/espressomd/docker/test/centos-python3:7-0506a04e4dc4e2cb6345f50884a68c22b8472a58` image. I regenerated it locally from scratch with kaniko v0.15 and then provided the path to the cache to upload it to GitLab-CI. But CI with kaniko v0.15 failed when pulling that new image with the same error message. I deleted the image again and tried to re-generate it in GitLab-CI, but it still failed as it pulled the corrupted image from elsewhere.

Could we have a look on Monday? The caching mechanism doesn't work as I understood it, and it is not described in our CI documentation.

**Comment by mkuron** [comment]
There's  espressomd/docker/cache, which you can clear by clicking the trashcan icon next to it. That is what Kaniko uses to store its cache.

**Comment by jngrad** [comment]
Nevermind, I didn't realize the intermediate layers were stored in a different folder of the cache registry. Deleting the corrupted layers seems to solve the issue. We'll keep the v0.15 for now, it's from December.

**Comment by hmenke** [comment]
I would have expect blas and lapack to already be available, because these are mandatory dependencies of scipy.

**Comment by jngrad** [comment]
@hmenke scipy was added less than 2 weeks ago (#153), but even with scipy you'll need the dev versions of blas and lapack installed, otherwise CMake will expect you to provide a search path to find the blas/lapack shared objects. In addition, for some OSes like Fedora, scipy only installs openblas ([RPM dependencies](https://fedora.pkgs.org/31/fedora-x86_64/python3-scipy-1.2.1-5.fc31.x86_64.rpm.html)); there is a lapack wrapper shared object within `/usr/lib64/python3.7/site-packages/scipy/` but that's it.
@mkuron looks like 1a87381 worked: we can skip the 4-hours long Intel compilation with by re-using cached layers, reducing the time build down to 90 min ([jobs/203132](https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/203132)); we might as well run `intel:19` every time now instead of manually triggering it.

**Comment by jngrad** [comment]
The intel compiler in `intel:19` can only be used as root. Also, the intel libraries folder at `/opt/intel/compilers_and_libraries_2019.5.281/linux/` takes 12GB of space. Do we really need all of them?

**Comment by mkuron** [comment]
`rm -r /opt/intel/compilers_and_libraries_*/linux/{daal,mkl,ipp,tbb} /opt/intel/{intelpython*,debugger*,documentation*,advisor*,inspector*,clck*,itac*,conda_channel}` decreases the size from 18 GB to 3.7 GB.
`chmod 777 /tmp` fixes the permissions issue.

**Comment by RudolfWeeber** [comment]
On Tue, Feb 11, 2020 at 02:25:43AM -0800, Michael Kuron wrote:
> `rm -r /opt/intel/compilers_and_libraries_*/linux/{daal,mkl,ipp,tbb} /opt/intel/{intelpython*,debugger*,documentation*,advisor*,inspector*,clck*,itac*,conda_channel}` decreases the size from 18 GB to 3.7 GB.
> `chmod 777 /tmp` fixes the permissions issue.
The future of intel compiler support needs to be discussed at the Espresso meeting.

**Comment by mkuron** [comment]
It's the default compiler on some HPC clusters and it shares the same frontend with many other compilers (IBM, Cray, PGI), so we definitely need to continue to test releases against it.

**Comment by jngrad** [comment]
The `intel:19` image now builds and the compiler layer is only 1.4 GB. Python tests run fine on it.

**Pull request merged**
