### PR TITLE
Make use of new Gitlab CI features and remove unused dockerfiles

### PR DESCRIPTION
**Pull request by mkuron**
DAG (https://docs.gitlab.com/ee/ci/directed_acyclic_graph/, https://docs.gitlab.com/ee/ci/yaml/README.html#needs): this allows independent jobs to run in parallel, potentially speeding up things.

Per-job timeouts (https://docs.gitlab.com/ee/ci/yaml/#timeout): we know which jobs can take longer, so we can automatically kill those that shouldn't take long if they get stuck.

Interruptible (https://docs.gitlab.com/ee/ci/yaml/#interruptible): stop jobs when a new commit is pushed.

Docker registry clean up: reduce the amount of storage occupied by our Docker registry.

Remove unused or redundant Docker images: `debian:9`, `cuda:10.1`, `cuda:tutorials`.

### CODE REVIEW

**Comment by mkuron** [comment]
The `needs` on the deploy jobs is fine. It seems like earlier stages still have higher priority.

**Comment by mkuron** [comment]
Done from my side, @jngrad.

**Comment by jngrad** [comment]
@mkuron the timeout is still too short ([logfile](https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/165230)), I'll change it to 1h

**Comment by mkuron** [comment]
The issue with the manual jobs is https://gitlab.com/gitlab-org/gitlab/issues/31264. We can re-enable the dependencies once that is fixed.

**Pull request merged**
