### PR TITLE
Add scipy python module

### PR DESCRIPTION
**Pull request by jngrad**

### CODE REVIEW

**Comment by jngrad** [comment]
* the emulated images actually built, but the GitLab-CI DAG just skips the test stage
* the clang image is unable to reach the URL; it happened in the past from time to time but here it failed 3 times (the URL is reachable in my browser)
* the intel image couldn't contact the license server

**Comment by jngrad** [comment]
* the clang image can now reach the URL
* after clang passed the test stage, the DAG deadlock resolved itself (so we need to wait for all non-manual jobs to pass the test stage for the manual jobs to be able to start the test stage?)
* `elk` can build any QEMU image, the only thing we need to keep in mind is that the test stage for QEMU images cannot pass on `coyote10` (according to the logs, all other coyotes will do)
* the Intel compiler license server is still non-responsive; we should probably ping that server weekly

**Comment by mkuron** [comment]
Regarding Intel: the license server is responsive and you can actually run the Intel compiler on your desktop machine (`icpc --version` works). Not sure why it doesn't work from the Docker container.

**Comment by KaiSzuttor** [comment]
can this be merged?

**Comment by jngrad** [comment]
@KaiSzuttor I don't mind. We just need to remember to drop support for s390x on espresso 4.2.
@mkuron The HLRS licensing server seems to reject our requests

**Pull request merged**
