### PR TITLE
 QEMU containers: migrate to Python3 

### PR DESCRIPTION
**Pull request by jngrad**
Migrate QEMU containers to Python3 (espressomd/espresso#2694).
@mkuron

### CODE REVIEW

**Comment by jngrad** [comment]
1. The error message for arm containers was cryptic (before the retry)
2. The arm package `python3-vtk` is not available on [bionic](https://packages.ubuntu.com/bionic/python3-vtk7), [cosmic](https://packages.ubuntu.com/cosmic/python3-vtk7) but is available on  [disco](https://packages.ubuntu.com/disco/python3-vtk7)

I tried adding `disco main universe` to apt but there are too many dependencies which cannot be resolved without upgrading python3 itself to the disco version. Compiling VTK from sources requires OpenGL among other dependencies. I'm now testing disco as the base image instead of cosmic.

**Comment by jngrad** [comment]
The cryptic error messages in QEMU containers are really annoying ([`ubuntu:arm64`](https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/116455), [`ubuntu:ppc64le`](https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/116458)) and sometimes require multiple retries to disappear.

**Comment by mkuron** [comment]
Cosmic is probably out of support already, so feel free to upgrade to disco. 

The cryptic error message means that the Docker host doesn‘t have the binfmt_support package installed. Does it by chance only occur on the bwCloud runner? I tested it there yesterday and it worked, but I can check again tomorrow.

**Comment by mkuron** [comment]
@jngrad, I can't reproduce the cryptic error message in bwCloud. No idea what was wrong there yesterday. The `binfmt-support` package is properly installed in the cloud instance and I can manually start the exotic architecture Docker containers. Let me know if it happens again.

**Comment by jngrad** [comment]
I built espresso and ran the tests locally for arm64, armhf, ppc64le, i386, s390x using disco as the base. There was no issue for disco/i386/armhf, but electrostatics-related and `lb_stokes` tests timed out in arm64/ppc64le/s390x. Here's a sample of the error messages:
`s390x` (ctest stops prematurely around ~90 out of 132 tests)
```
/usr/bin/mpiexec: relocation error: /usr/lib/s390x-linux-gnu/openmpi/lib/openmpi3/mca_iof_hnp.so:
symbol __errno_location version GLIBC_2.2 not defined in file libpthread.so.0 with link time reference
```
`arm64` and `ppc64le`
```
[8aba3ebf5886:17687] Read -1, expected 10112, errno = 38
/usr/lib/python3/dist-packages/numpy/core/getlimits.py:53: RuntimeWarning: divide by zero encountered in log10
  self.precision = int(-log10(self.eps))
```

**Comment by RudolfWeeber** [comment]
On Wed, May 22, 2019 at 05:27:10AM -0700, Jean-Noël Grad wrote:
> I built espresso and ran the tests locally for arm64, armhf, ppc64le, i386, s390x using disco as the base. There was no issue for disco/i386/armhf, but electrostatics-related and `lb_stokes` tests timed out in arm64/ppc64le/s390x. Here's a sample of the error messages:
In espressomd/espreso's CI, the tests marekd as LONG are not run on exotic architectures. 
via
export check_skip_long=true

**Comment by mkuron** [comment]
The relocation error can be fixed by a simple environment variable: https://github.com/espressomd/espresso/pull/2790

**Comment by jngrad** [comment]
I tried again with `check_python_skip_long`, but it didn't remove all the failing tests.

**Comment by RudolfWeeber** [comment]
On Wed, May 22, 2019 at 07:47:41AM -0700, Jean-Noël Grad wrote:
> I tried again with `check_python_skip_long`, but it didn't remove all the failing tests.
Can you use the exact CI template from espressomd/espresso for the exotic archs?
If you're running this on an Icp machine, maybe
condor_drain `hostname`
as well.

**Comment by jngrad** [comment]
Thanks for the suggestions @mkuron @RudolfWeeber, no more failing tests, however in `s390x` ctest still stops prematurely at 89 out of 127 tests without printing any error message:
```
 88/127 Test  #29: integrate ...............................   Passed    2.34 sec
 89/127 Test  #69: mmm1d ...................................   Passed    2.09 sec

100% tests passed, 0 tests failed out of 89
```
The return code is 0. I just checked out a nightly build on espressomd/espresso and it turns out this is also happening with the current `s390x` container ([logfile that stops at 28/129 python checks](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/116521)).

**Pull request merged**
