### PR TITLE
push image to dockerhub if credentials are provided.

### PR DESCRIPTION
**Pull request by KaiSzuttor**

### CODE REVIEW

**Comment by KaiSzuttor** [comment]
i have to push to a branch to be able to test the push to dockerhub

**Comment by KaiSzuttor** [comment]
it works on my repo https://github.com/KaiSzuttor/docker/runs/557918306

**Comment by KaiSzuttor** [comment]
the image name for travis has to be changed to ```espressomd/docker-ubuntu-travis```

**Comment by jngrad** [comment]
Just to clarify:
- we use tested SHA in `.gitlab-ci.yml`, but here we always upload the Travis image automatically?
- do we upload only the Travis image or all images?

**Comment by KaiSzuttor** [comment]
i don't understand your first question. We upload all images to dockerhub

**Comment by KaiSzuttor** [comment]
the images on dockerhub also have the sha tag, maybe that answers your question

**Comment by jngrad** [comment]
oh I overlooked the `${tag}` variable, nevermind

**Comment by jngrad** [comment]
> the image name for travis has to be changed to `espressomd/docker-ubuntu-travis:SHA`

I'll update `.travis.yml` on espressomd/espresso whenever the dockerfile gets new packages.

**Comment by KaiSzuttor** [comment]
Allright, then lets merge this

**Comment by KaiSzuttor** [comment]
I think you have to update ```maintainer/CI/build_docker.sh``` in the espresso repo

**Comment by jngrad** [comment]
I'll update it in the currently opened CMake refactor PR.

**Pull request merged**
